steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-docker.pkg.dev/tonofshell-analyses/r-analysis/remoter', '-f', 'remoter/Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/tonofshell-analyses/r-analysis/remoter']